name: 'ğŸš€ Publish'

on:
  push:
    branches:
      - master

jobs:
  release:
    name: ğŸš€ Publish
    runs-on: macos-13
    steps:
      - name: ğŸ“š checkout
        uses: actions/checkout@v2.4.2
      - name: ğŸŸ¢ node
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - name: ğŸš€ Build & Publish
        run: yarn install && cd webui && yarn install && yarn run export && cd .. && yarn build && yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
